services:
  rss:
    image: nginx:alpine
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - notion

  notion:
    build: .
    volumes:
      - ./public:/app/public
    env_file:
      - .env
    restart: unless-stopped
