server {
    listen 80;
 
    root /usr/share/nginx/html;
    index index.html;
 
    # Serve the RSS feed file with the correct content type
    location = /feed {
        default_type application/rss+xml;
    }
 
    location / {
        try_files $uri $uri/ =404;
    }
}
 
